# Generated by Django 2.0.3 on 2018-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_likes'),
        ('users', '0004_auto_20180521_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(related_name='liked_by', to='posts.Post'),
        ),
    ]
